### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mohammadhadiaarabi** [brainlife/app-qsiprep#1]
Dear Developer,
When I this app, I see this error:
+ set -e
+ export 'FREESURFER_LICENSE=hayashis@iu.edu 29511 *CPmh9xvKQKHE FSg0ijTusqaQc'
+ FREESURFER_LICENSE='hayashis@iu.edu 29511 *CPmh9xvKQKHE FSg0ijTusqaQc'
+ echo hayashis@iu.edu 29511 '*CPmh9xvKQKHE' FSg0ijTusqaQc
+ bl2bids
./main: line 11: bl2bids: command not found

I would be appreciated if you help me to fix this error.
Best,
Mohammad

**Comment by soichih** [comment]
It looks like the resource this is running on doesn't have the latest version of abcd hook script installed. Which resource are you having this issue on?

**Comment by mohammadhadiarabi** [comment]
I tried use singularity in my local system.

**Comment by soichih** [comment]
Oh I see. If you are just trying to run qsiprep locally, then you can just run it directly?

**Comment by mohammadhadiarabi** [comment]
No. I used ./main code for running it.

**Comment by giulia-berto** [comment]
Hi @mohammadhadiarabi, sorry I missed this message. Thanks for the feedback, in this case just running ./main will not work because the bl2bids command is not recognized outside brainlife (I just updated the documentation). If your inputs are already organized in a bids folder, you just need to run what @soichih was saying (in $optional you can put any additional command-line argument you want, see https://qsiprep.readthedocs.io/en/latest/usage.html#).

**Comment by francopestilli** [comment]
I am closing this old issue

**Comment by francopestilli** [comment]
Closed
